leboncoin_index:
    path:     /
    defaults: { _controller: LeBonCoinBundle:Home:index }

leboncoin_edit_advert:
    path:     /advert/edit
    defaults: { _controller: LeBonCoinBundle:Advert:Edit }
