leboncoin_index:
    path:     /
    defaults: { _controller: LeBonCoinBundle:Home:index }

leboncoin_edit_advert:
    path:     /advert/edit
    defaults: { _controller: LeBonCoinBundle:Advert:edit }

leboncoin_show_advert:
    path:     /advert/show/{id}
    defaults: { _controller: LeBonCoinBundle:Advert:show, id: null }

leboncoin_search:
    path:     /search
    defaults: { _controller: LeBonCoinBundle:Search:index }