leboncoin_index:
    path:     /
    defaults: { _controller: LeBonCoinBundle:Home:index }

leboncoin_edit:
    path:     /edit/{id}
    defaults: { _controller: LeBonCoinBundle:Advert:Edit, id: null }
